CREATE TABLE "CATEGORIES" (
  "ID"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "NAME"  TEXT,
  "PARENT" INTEGER,
  "PATH"  TEXT,
  "COLOR" TEXT,
  "ICON" BLOB
);

CREATE TABLE "PRODUCTS" (
  "ID"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "CATEGORY"  INTEGER,
  "NAME"  TEXT,
  "SOURCEPATH"  TEXT NOT NULL,
  "TARGETDIRNAME"  TEXT NOT NULL,
  "TARGETPATH"  TEXT,
  "URL"  TEXT,
  "TAGS"  TEXT,
  "DESCRIPTION"  TEXT,
  "TIMESTAMP"  DATETIME,
  "STATUS"  INTEGER
);

CREATE TABLE "TAGS" (
  "ID"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "TAG" TEXT NOT NULL,
  "COUNT" INTEGER,
  "PRODUCT_ID" INTEGER
);

CREATE TABLE "OPTIONS" (
  "NAME" TEXT PRIMARY KEY NOT NULL,
  "VALUE" TEXT
);

CREATE INDEX "CATEGORIES_NAME_IDX1" ON "PRODUCTS" ("NAME");
CREATE INDEX "DIRS_NAME_IDX2" ON "PRODUCTS" ("NAME");
CREATE INDEX "DIRS_TIMESTAMP_IDX1" ON "PRODUCTS" ("TIMESTAMP" DESC);
CREATE INDEX "TAGS_TAG_IDX1" ON "TAGS" ("TAG");
CREATE INDEX "TAGS_PRODUCT_IDX1" ON "TAGS" ("PRODUCT_ID");

INSERT INTO "OPTIONS" ("NAME", "VALUE") VALUES ("DBVERSION", "1");

INSERT INTO "CATEGORIES" ("ID", "NAME", "PATH", "COLOR", "ICON", "PARENT") VALUES ('1', 'Applications', '', NULL, '4', '-1');
INSERT INTO "CATEGORIES" ("ID", "NAME", "PATH", "COLOR", "ICON", "PARENT") VALUES ('2', 'E-books', '', '#E5E5E5', '22', '-1');
INSERT INTO "CATEGORIES" ("ID", "NAME", "PATH", "COLOR", "ICON", "PARENT") VALUES ('3', 'Games', '', '#D5FBD2', '8', '-1');
INSERT INTO "CATEGORIES" ("ID", "NAME", "PATH", "COLOR", "ICON", "PARENT") VALUES ('4', 'Movies', '', '#F5F4C0', '13', '-1');
INSERT INTO "CATEGORIES" ("ID", "NAME", "PATH", "COLOR", "ICON", "PARENT") VALUES ('5', 'HD', '', '#F5F4C0', '13', '4');
INSERT INTO "CATEGORIES" ("ID", "NAME", "PATH", "COLOR", "ICON", "PARENT") VALUES ('6', 'Series', '', '#FFE1F1', '13', '4');
INSERT INTO "CATEGORIES" ("ID", "NAME", "PATH", "COLOR", "ICON", "PARENT") VALUES ('7', 'Musics', '', '#EFDEFA', '15', '-1');

