CREATE TABLE "CATEGORIES" (
"ID"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"NAME"  TEXT,
"PARENT" INTEGER,
"PATH"  TEXT,
"COLOR" TEXT,
"ICON" BLOB
);

CREATE TABLE "DIRS" (
"ID"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"CATEGORY" INTEGER,
"NAME"  TEXT,
"SOURCEPATH"  TEXT NOT NULL,
"TARGETDIRNAME"  TEXT NOT NULL,
"TARGETPATH"  TEXT,
"URL"  TEXT,
"TAGS" TEXT,
"DESCRIPTION"  TEXT,
"TIMESTAMP" DATETIME,
"STATUS" INTEGER
);

CREATE TABLE "TAGS" (
  "ID"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "TAG" TEXT NOT NULL,
  "PRODUCT_ID" INTEGER
);

CREATE TABLE "OPTIONS" (
  "NAME" TEXT PRIMARY KEY NOT NULL,
  "VALUE" TEXT
);

CREATE INDEX "CATEGORIES_NAME_IDX1" ON "DIRS" ("NAME");
CREATE INDEX "DIRS_NAME_IDX2" ON "DIRS" ("NAME");
CREATE INDEX "DIRS_TIMESTAMP_IDX1" ON "DIRS" ("TIMESTAMP" DESC);
CREATE INDEX "TAGS_TAG_IDX1" ON "TAGS" ("TAG");
CREATE INDEX "TAGS_PRODUCT_IDX1" ON "TAGS" ("PRODUCT_ID");

INSERT INTO "OPTIONS" ("NAME", "VALUE") VALUES ("DBVERSION", "1");

