CREATE TABLE "ProductImage" (
  "ID"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "PRODUCT_ID" INTEGER NOT NULL,
  "FILENAME" TEXT,
  "DATA" BLOB
);

CREATE TABLE "ProductInfo" (
  "ID"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "PRODUCT_ID" INTEGER NOT NULL,
  "NFO" BLOB
);
